# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-12 07:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docinfo',
            name='url_path',
            field=models.CharField(default='', max_length=60, verbose_name='文档存放路径'),
            preserve_default=False,
        ),
    ]
